"""
build_form.py — regenerates the product sections of index.html from catalog.xlsx.

Run this after editing catalog.xlsx (new product, price change, restock, etc.):

    python build_form.py

What it does:
  1. Reads the "Catalog" sheet from catalog.xlsx.
  2. Any row with Stock == 0 is force-flipped to Active = N (written back to the file).
  3. Recomputes the "WA Key" column for every row and writes it back
     (e.g. "Mustard Oil — Organic (1 L)"). Never edit this column by hand.
  4. Rebuilds the category sections and the PRODUCTS JS array inside index.html,
     replacing only the content between the CATALOG:* markers.

Only rows with Active == Y end up on the form.
"""
import re
import sys
from pathlib import Path

import openpyxl

BASE_DIR = Path(__file__).resolve().parent
CATALOG_FILE = BASE_DIR / "catalog.xlsx"
INDEX_FILE = BASE_DIR / "index.html"
ORDERS_TEMPLATE_FILE = BASE_DIR / "python" / "orders_template.xlsx"
SHEET_NAME = "Catalog"

ORDERS_META_COLS = ["Customer Name", "Phone", "Pincode", "Address", "Notes", "Order Date"]

HEADERS = [
    "Product Name", "Category", "Display Name", "Unit", "Pack Size",
    "MRP", "HSN/SAC", "GST%", "Stock", "Active", "WA Key", "Notes",
]

# Section heading shown on the form for a raw Category value.
# Anything not listed here falls back to the raw Category text.
CATEGORY_LABELS = {
    "Oils - Organic": "Cold-Pressed Oils — Organic",
    "Oils - Regular": "Cold-Pressed Oils — Regular",
    "Ghee": "Ghee",
    "Flour": "Flour",
    "Dal": "Dal & Pulses — Organic",
    "Rice": "Rice — Organic",
    "Spices - Whole": "Spices — Whole",
    "Spices - Ground": "Spices — Ground",
}

CATEGORIES_START = "<!-- CATEGORIES_START (auto-generated by build_form.py — do not edit by hand) -->"
CATEGORIES_END = "<!-- CATEGORIES_END -->"
PRODUCTS_START = "// CATALOG_START"
PRODUCTS_END = "// CATALOG_END"


def slugify(text):
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "cat"


def make_id(display_name, pack_size, used):
    base = re.sub(r"[^a-z0-9]", "", (display_name + pack_size).lower())[:14] or "item"
    candidate = base
    n = 2
    while candidate in used:
        candidate = f"{base}{n}"
        n += 1
    used.add(candidate)
    return candidate


def js_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def format_number(value):
    try:
        f = float(value)
    except (TypeError, ValueError):
        return value
    return int(f) if f == int(f) else f


def load_catalog():
    if not CATALOG_FILE.exists():
        sys.exit(f"Catalog file not found: {CATALOG_FILE}")

    wb = openpyxl.load_workbook(CATALOG_FILE)
    if SHEET_NAME not in wb.sheetnames:
        sys.exit(f'Sheet "{SHEET_NAME}" not found in {CATALOG_FILE.name}')
    ws = wb[SHEET_NAME]

    header_row = [c.value for c in ws[1]]
    missing = [h for h in HEADERS if h not in header_row]
    if missing:
        sys.exit(f"catalog.xlsx is missing required column(s): {missing}")
    col = {name: header_row.index(name) for name in HEADERS}

    rows = []
    changed = False
    for r in range(2, ws.max_row + 1):
        values = [ws.cell(row=r, column=col[h] + 1).value for h in HEADERS]
        if all(v is None or str(v).strip() == "" for v in values):
            continue
        record = dict(zip(HEADERS, values))

        try:
            stock = float(record["Stock"] or 0)
        except (TypeError, ValueError):
            stock = 0
        active = str(record["Active"] or "").strip().upper()
        if stock <= 0 and active != "N":
            active = "N"
            ws.cell(row=r, column=col["Active"] + 1, value="N")
            changed = True
        record["Active"] = active

        display = str(record["Display Name"] or "").strip() or str(record["Product Name"] or "").strip()
        pack = str(record["Pack Size"] or "").strip()
        wa_key = f"{display} ({pack})" if pack else display
        if str(record["WA Key"] or "") != wa_key:
            ws.cell(row=r, column=col["WA Key"] + 1, value=wa_key)
            changed = True
        record["WA Key"] = wa_key
        record["Display"] = display

        rows.append(record)

    if changed:
        wb.save(CATALOG_FILE)

    return rows


def build_blocks(rows):
    categories = []  # preserve first-seen order in the sheet
    grid_id_for = {}
    for r in rows:
        cat = str(r["Category"] or "").strip()
        if cat not in grid_id_for:
            grid_id_for[cat] = f"pg-{slugify(cat)}"
            categories.append(cat)

    used_ids = set()
    cat_html_lines = []
    js_lines = []
    active_count = 0
    for cat in categories:
        active_in_cat = [
            r for r in rows
            if str(r["Category"] or "").strip() == cat and r["Active"] == "Y"
        ]
        if not active_in_cat:
            continue  # don't show an empty section header

        label = CATEGORY_LABELS.get(cat, cat)
        grid_id = grid_id_for[cat]
        cat_html_lines.append(f'    <div class="category-label">{label}</div>')
        cat_html_lines.append(f'    <div class="product-grid" id="{grid_id}"></div>')
        cat_html_lines.append("")

        for r in active_in_cat:
            pid = make_id(r["Display"], str(r["Pack Size"] or ""), used_ids)
            mrp = format_number(r["MRP"])
            js_lines.append(
                f'  ["{pid}", "{grid_id}", "{js_escape(r["Display"])}", '
                f'"{js_escape(str(r["Pack Size"]))}", {mrp}],'
            )
            active_count += 1

    while cat_html_lines and cat_html_lines[-1] == "":
        cat_html_lines.pop()

    return "\n".join(cat_html_lines), "\n".join(js_lines), active_count, len([c for c in categories if any(
        str(r["Category"] or "").strip() == c and r["Active"] == "Y" for r in rows)])


def replace_block(html, start_marker, end_marker, new_body):
    pattern = re.compile(re.escape(start_marker) + r".*?" + re.escape(end_marker), re.DOTALL)
    if not pattern.search(html):
        raise RuntimeError(f"Markers {start_marker!r} / {end_marker!r} not found in index.html")
    replacement = f"{start_marker}\n{new_body}\n{end_marker}"
    return pattern.sub(replacement, html, count=1)


def rebuild_orders_template(rows):
    """Regenerate python/orders_template.xlsx so its product columns match catalog.xlsx exactly."""
    product_cols = [str(r["Product Name"]).strip() for r in rows]
    all_cols = ORDERS_META_COLS + product_cols

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Orders"
    ws.append(all_cols)

    from openpyxl.styles import Font, PatternFill
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="3A5428")

    ORDERS_TEMPLATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    wb.save(ORDERS_TEMPLATE_FILE)
    print(f"Wrote {len(product_cols)} product column(s) to {ORDERS_TEMPLATE_FILE.relative_to(BASE_DIR)}")


def main():
    rows = load_catalog()
    cat_block, js_lines, active_count, category_count = build_blocks(rows)

    if active_count == 0:
        sys.exit("No active products found in catalog — aborting so index.html isn't wiped out.")

    html = INDEX_FILE.read_text(encoding="utf-8")
    html = replace_block(html, CATEGORIES_START, CATEGORIES_END, cat_block)
    html = replace_block(
        html, PRODUCTS_START, PRODUCTS_END,
        "const PRODUCTS = [\n  // [id, category_grid_id, name, unit, price]\n" + js_lines + "\n];",
    )
    INDEX_FILE.write_text(html, encoding="utf-8")

    print(f"Wrote {active_count} active product(s) across {category_count} category section(s) to {INDEX_FILE.name}")

    rebuild_orders_template(rows)


if __name__ == "__main__":
    main()
